"""Drop the vehicle_type CHECK constraint from vehicles.

vehicle_type is validated by the Pydantic ``VehicleType`` Literal on every write
path (the API is the sole writer). The redundant DB-level CHECK forced a full
table rebuild for every new vehicle type. Dropping it makes future type additions
code-only (Literal + frontend list), no migration — 'ATV' is added alongside this
migration as the first such code-only type. Pydantic remains the gate.

Dialect-aware:
  * PostgreSQL — ``ALTER TABLE ... DROP CONSTRAINT`` (found by definition, so it
    works whether the constraint is named ``check_vehicle_type`` or autogenerated).
  * SQLite — no in-place CHECK drop exists, so the table is rebuilt via
    live-DDL-swap: the existing ``CREATE TABLE`` is read from sqlite_master, its
    ``vehicle_type`` CHECK clause is stripped, and the table is rebuilt
    (create → copy → drop → rename), preserving every column/PK/default/FK exactly.
    vehicles is an FK PARENT (service_visits, fuel_records, telemetry, …), so the
    rebuild runs with ``foreign_keys=OFF`` (otherwise DROP TABLE would cascade the
    children) inside an explicit transaction, then re-verifies with
    ``foreign_key_check`` before commit.

Idempotent — skips when no vehicle_type CHECK is present (true on fresh
create_all installs, since the model no longer declares it, and on re-runs).
Forward-only.

Declares no ``FATAL``, so a failure here does not by itself stop the app from
booting. Do NOT read that as "a failure is contained": the runner aborts the
whole run on any exception, so everything queued behind this migration is
skipped too — including 080, 082 and 083, which ARE ``FATAL = True`` because
the models declare their columns non-nullable. A failure here therefore
disarms them and boots the app against a schema it cannot satisfy. That is
what made the rc2 breakage present as a hard crash rather than a stale CHECK.
Keep this migration's DDL handling conservative for that reason.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from sqlalchemy import create_engine, inspect, text

# Matches the vehicle_type CHECK whether written as a named table constraint
# (`CONSTRAINT check_vehicle_type CHECK (...)`) or an unnamed inline column
# constraint (`CHECK (vehicle_type IN (...))`). The inner IN-list has exactly one
# paren level, so [^)]* is safe up to the list's closing paren.
_CHECK_RE = re.compile(
    r"(?:CONSTRAINT\s+\w+\s+)?CHECK\s*\(\s*vehicle_type\s+IN\s*\([^)]*\)\s*\)",
    re.IGNORECASE | re.DOTALL,
)


def _strip_check(ddl: str) -> str:
    """Remove the vehicle_type CHECK clause and repair the comma it leaves behind.

    The clause appears in the wild in two shapes, and which one an install has
    depends on how its ``vehicles`` table was built:

      * inline on the column — ``vehicle_type VARCHAR(20) NOT NULL CHECK (...)``,
        produced by the early hand-written CREATE TABLE migrations. Deleting the
        clause leaves ``NOT NULL ,`` — already valid, nothing to repair.
      * a table-level constraint on its own — ``, CHECK (...),`` — produced by
        ``create_all`` for the ``CheckConstraint`` the model declared from
        v2.14.0 until v3.0.0. Deleting the clause strands its comma, giving
        ``,  ,`` mid-table or ``,  )`` at the end. Both are syntax errors, and
        SQLite reports them as ``near ","`` / ``near ")"`` (reported by
        @SCDT95 against v3.0.0-rc2, issue #137).

    So the comma cannot be folded into ``_CHECK_RE``: in the inline shape the
    trailing comma is the *column separator* and eating it welds two column
    definitions together. Strip first, then normalise — that is safe for both.
    """
    out = _CHECK_RE.sub("", ddl)
    # Constraint sat between two others: ", CHECK (...)," -> ",  ," -> ","
    out = re.sub(r",\s*,", ",", out)
    # Constraint was the last item in the table body: ", CHECK (...))" -> ",  )" -> ")"
    # Safe against a real trailing comma inside a list such as PRIMARY KEY (a, b),
    # because there the comma is followed by an identifier, not the closing paren.
    out = re.sub(r",\s*\)", "\n)", out)
    return out


def _get_fallback_engine():
    db_path = os.environ.get("DATABASE_PATH")
    if db_path:
        return create_engine(f"sqlite:///{db_path}")
    data_dir = Path(os.getenv("DATA_DIR", "/data"))
    return create_engine(f"sqlite:///{data_dir / 'mygarage.db'}")


def upgrade(engine=None):
    if engine is None:
        engine = _get_fallback_engine()
    if not inspect(engine).has_table("vehicles"):
        return
    if engine.dialect.name == "postgresql":
        _upgrade_pg(engine)
    else:
        _upgrade_sqlite(engine)


def _upgrade_pg(engine):
    with engine.begin() as conn:
        row = conn.execute(
            text(
                """
                SELECT conname FROM pg_constraint
                WHERE conrelid = 'vehicles'::regclass AND contype = 'c'
                  AND pg_get_constraintdef(oid) LIKE '%vehicle_type%'
                """
            )
        ).fetchone()
        if row:
            conn.execute(text(f'ALTER TABLE vehicles DROP CONSTRAINT "{row[0]}"'))


def _upgrade_sqlite(engine):
    with engine.connect() as conn:
        ddl = conn.exec_driver_sql(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='vehicles'"
        ).scalar()
        if not ddl or not _CHECK_RE.search(ddl):
            return  # no vehicle_type CHECK present — fresh install or already dropped
        index_sqls = [
            r[0]
            for r in conn.exec_driver_sql(
                "SELECT sql FROM sqlite_master WHERE type='index' "
                "AND tbl_name='vehicles' AND sql IS NOT NULL"
            ).fetchall()
        ]

    new_ddl = _strip_check(ddl)
    new_ddl = re.sub(
        r'CREATE\s+TABLE\s+"?vehicles"?',
        'CREATE TABLE "vehicles_new"',
        new_ddl,
        count=1,
        flags=re.IGNORECASE,
    )

    raw = engine.raw_connection()
    try:
        dbapi = raw.driver_connection  # underlying sqlite3.Connection
        prev_iso = dbapi.isolation_level
        dbapi.isolation_level = None  # autocommit — we drive the transaction explicitly
        cur = dbapi.cursor()
        # foreign_keys can only be toggled outside a transaction; do it first, then
        # BEGIN. With FKs off, DROP TABLE vehicles won't cascade-delete the children.
        cur.execute("PRAGMA foreign_keys=OFF")
        cur.execute("BEGIN")
        try:
            cur.execute("DROP TABLE IF EXISTS vehicles_new")
            cur.execute(new_ddl)
            cur.execute("INSERT INTO vehicles_new SELECT * FROM vehicles")
            cur.execute("DROP TABLE vehicles")
            cur.execute("ALTER TABLE vehicles_new RENAME TO vehicles")
            for isql in index_sqls:
                cur.execute(isql)
            violations = cur.execute("PRAGMA foreign_key_check").fetchall()
            if violations:
                raise RuntimeError(f"FK violations after vehicles rebuild: {violations}")
            cur.execute("COMMIT")
        except Exception:
            cur.execute("ROLLBACK")
            raise
        finally:
            cur.execute("PRAGMA foreign_keys=ON")
            dbapi.isolation_level = prev_iso
    finally:
        raw.close()


def downgrade():
    print("Downgrade not supported: re-adding a CHECK would reject any new-type rows.")


if __name__ == "__main__":
    upgrade()
